require('dotenv').config();

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const express = require('express');
const helmet = require('helmet');
const cookieParser = require('cookie-parser');
const rateLimit = require('express-rate-limit');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const multer = require('multer');
const store = require('./store');
const mailer = require('./mailer');

const app = express();
const PORT = process.env.PORT || 3000;

function hashLicenseKey(key) {
  return crypto.createHash('sha256').update(String(key)).digest('hex');
}

/* ------------------------------------------------------------------ *
 * 1. LICENSE VERIFICATION (SOHAM.LICENSE) -- with zero-config fallback
 * ------------------------------------------------------------------ *
 * If you set LICENSE_KEY + LICENSE_KEY_HASH yourself (recommended for
 * a real deployment), those are used and must match. If you don't set
 * them at all, the server generates a one-off pair automatically so
 * it still boots -- convenient for a quick first deploy, but note:
 * that generated key only lives in this process's memory, so it is
 * NOT a real access-control key and won't survive a restart. Set your
 * own via `node scripts/generate-license-hash.js` before going live.
 * ------------------------------------------------------------------ */

let licenseAutoGenerated = false;
if (!process.env.LICENSE_KEY || !process.env.LICENSE_KEY_HASH) {
  const autoKey = crypto.randomBytes(24).toString('hex');
  process.env.LICENSE_KEY = autoKey;
  process.env.LICENSE_KEY_HASH = hashLicenseKey(autoKey);
  licenseAutoGenerated = true;
  console.log('[SOHAM.LICENSE] LICENSE_KEY / LICENSE_KEY_HASH not set -- auto-generated one for this session only.');
  console.log('[SOHAM.LICENSE] Set your own permanent pair before real deployment: npm run generate:license-hash');
}

function verifyLicense() {
  const suppliedHash = hashLicenseKey(process.env.LICENSE_KEY);
  const expectedHash = process.env.LICENSE_KEY_HASH;
  const a = Buffer.from(suppliedHash, 'hex');
  const b = Buffer.from(expectedHash, 'hex');
  const valid = a.length === b.length && crypto.timingSafeEqual(a, b);
  return valid ? { valid: true } : { valid: false, reason: 'LICENSE_KEY does not match LICENSE_KEY_HASH.' };
}

const licenseStatus = verifyLicense();

if (licenseStatus.valid) {
  console.log('[SOHAM.LICENSE] License verified. Starting server normally.');
} else {
  console.error(`[SOHAM.LICENSE] License check FAILED: ${licenseStatus.reason}`);
}

app.use((req, res, next) => {
  if (licenseStatus.valid) return next();
  res.status(503).type('html').send(`
    <!doctype html>
    <html><head><meta charset="utf-8"><title>License Invalid</title></head>
    <body style="font-family: sans-serif; max-width: 640px; margin: 80px auto; color:#2B2418;">
      <h1>Service unavailable</h1>
      <p>This deployment's license key could not be verified.</p>
      <p style="color:#888; font-size: 13px;">Reason: ${licenseStatus.reason}</p>
    </body></html>
  `);
});

/* ------------------------------------------------------------------ *
 * 2. ADMIN CREDENTIALS -- with zero-config fallback
 * ------------------------------------------------------------------ *
 * Set ADMIN_USERNAME, ADMIN_PASSWORD_HASH and JWT_SECRET yourself for
 * a real deployment (see scripts/generate-admin-hash.js). If you
 * don't, a random password is generated and printed ONCE to the
 * server logs so you can still log in -- but it changes on every
 * restart and anyone with log access can read it. Fine for testing,
 * not for a live admissions site.
 * ------------------------------------------------------------------ */

if (!process.env.JWT_SECRET) {
  process.env.JWT_SECRET = crypto.randomBytes(48).toString('hex');
}
if (!process.env.ADMIN_USERNAME) {
  process.env.ADMIN_USERNAME = 'admin';
}
if (!process.env.ADMIN_PASSWORD_HASH) {
  const autoPassword = crypto.randomBytes(9).toString('hex');
  process.env.ADMIN_PASSWORD_HASH = bcrypt.hashSync(autoPassword, 10);
  console.log('\n==================================================');
  console.log('[SOHAM.ADMIN] No ADMIN_PASSWORD_HASH set -- auto-generated credentials for this session:');
  console.log(`   Username: ${process.env.ADMIN_USERNAME}`);
  console.log(`   Password: ${autoPassword}`);
  console.log('   This password changes every restart. Set your own with:');
  console.log('   node scripts/generate-admin-hash.js "YourStrongPassword"');
  console.log('==================================================\n');
}

const JWT_SECRET = process.env.JWT_SECRET;

/* ------------------------------------------------------------------ *
 * 3. CORE MIDDLEWARE
 * ------------------------------------------------------------------ */

app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());

/* ------------------------------------------------------------------ *
 * 4. FILE UPLOADS (admission proof photos -- optional, image only)
 * ------------------------------------------------------------------ */

const UPLOAD_DIR = path.join(__dirname, 'data', 'uploads');
fs.mkdirSync(UPLOAD_DIR, { recursive: true });

const upload = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => cb(null, UPLOAD_DIR),
    filename: (req, file, cb) => {
      const ext = path.extname(file.originalname).toLowerCase();
      cb(null, `${crypto.randomUUID()}${ext}`);
    }
  }),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB
  fileFilter: (req, file, cb) => {
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'];
    cb(null, allowed.includes(file.mimetype));
  }
});

// Uploaded proof photos are served back only under /uploads, never mixed with /public.
app.use('/uploads', express.static(UPLOAD_DIR));

/* ------------------------------------------------------------------ *
 * 5. ADMIN AUTH (JWT, httpOnly cookie)
 * ------------------------------------------------------------------ */

const ADMIN_COOKIE = 'soham_admin_token';
const ADMIN_TOKEN_TTL = '2h';

const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 10,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many login attempts. Please try again later.' }
});

function requireAdminAuth(req, res, next) {
  const token = req.cookies[ADMIN_COOKIE];
  if (!token) return res.status(401).json({ error: 'Not authenticated.' });
  try {
    req.admin = jwt.verify(token, JWT_SECRET);
    if (req.admin.role !== 'admin') throw new Error('wrong role');
    next();
  } catch {
    return res.status(401).json({ error: 'Invalid or expired session.' });
  }
}

function requireAdminAuthPage(req, res, next) {
  const token = req.cookies[ADMIN_COOKIE];
  if (!token) return res.redirect('/admin/login');
  try {
    const payload = jwt.verify(token, JWT_SECRET);
    if (payload.role !== 'admin') throw new Error('wrong role');
    next();
  } catch {
    return res.redirect('/admin/login');
  }
}

app.post('/api/admin/login', loginLimiter, async (req, res) => {
  const { username, password } = req.body || {};
  if (!username || !password) {
    return res.status(400).json({ error: 'Username and password are required.' });
  }

  const usernameMatches = username === process.env.ADMIN_USERNAME;
  const passwordMatches = usernameMatches
    ? await bcrypt.compare(password, process.env.ADMIN_PASSWORD_HASH)
    : false;

  if (!usernameMatches || !passwordMatches) {
    return res.status(401).json({ error: 'Invalid username or password.' });
  }

  const token = jwt.sign({ username, role: 'admin' }, JWT_SECRET, { expiresIn: ADMIN_TOKEN_TTL });
  res.cookie(ADMIN_COOKIE, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
    maxAge: 2 * 60 * 60 * 1000
  });
  res.json({ success: true });
});

app.post('/api/admin/logout', (req, res) => {
  res.clearCookie(ADMIN_COOKIE);
  res.json({ success: true });
});

app.get('/api/admin/me', requireAdminAuth, (req, res) => {
  res.json({ username: req.admin.username, emailNotificationsConfigured: mailer.isConfigured() });
});

/* ------------------------------------------------------------------ *
 * 6. ADMISSION WINDOW (June - August only)
 * ------------------------------------------------------------------ */

function isAdmissionOpen(date = new Date()) {
  const month = date.getMonth(); // 5 = Jun, 6 = Jul, 7 = Aug
  return month >= 5 && month <= 7;
}

app.get('/api/admission-status', (req, res) => {
  res.json({ open: isAdmissionOpen() });
});

/* ------------------------------------------------------------------ *
 * 7. ENQUIRIES -- with optional photo proof, saved to disk
 * ------------------------------------------------------------------ */

const enquiryLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 20,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many enquiries submitted from this connection. Please try again later.' }
});

app.post('/api/enquiry', enquiryLimiter, upload.single('photo'), (req, res) => {
  if (!isAdmissionOpen()) {
    if (req.file) fs.unlink(req.file.path, () => {});
    return res.status(403).json({
      error: 'Admissions are open only in June, July and August. Please check back during the admission window.'
    });
  }

  const { parentName, childName, phone, message } = req.body || {};
  if (!parentName || !childName || !phone) {
    if (req.file) fs.unlink(req.file.path, () => {});
    return res.status(400).json({ error: "Parent name, child's name and phone number are required." });
  }

  const enquiries = store.readAll('enquiries.json', []);
  const entry = {
    id: crypto.randomUUID(),
    parentName: String(parentName).slice(0, 200),
    childName: String(childName).slice(0, 200),
    phone: String(phone).slice(0, 40),
    message: String(message || '').slice(0, 1000),
    photoUrl: req.file ? `/uploads/${req.file.filename}` : null,
    submittedAt: new Date().toISOString(),
    status: 'new'
  };
  enquiries.unshift(entry);
  store.writeAll('enquiries.json', enquiries);

  mailer.notifyNewEnquiry(entry).catch(() => {}); // best-effort, never blocks the response

  res.json({ success: true });
});

app.get('/api/admin/enquiries', requireAdminAuth, (req, res) => {
  const { status, q, page = '1', pageSize = '25' } = req.query;
  let enquiries = store.readAll('enquiries.json', []);

  if (status && status !== 'all') {
    enquiries = enquiries.filter(e => e.status === status);
  }
  if (q) {
    const needle = String(q).toLowerCase();
    enquiries = enquiries.filter(e =>
      e.parentName.toLowerCase().includes(needle) ||
      e.childName.toLowerCase().includes(needle) ||
      e.phone.toLowerCase().includes(needle) ||
      (e.message || '').toLowerCase().includes(needle)
    );
  }

  const total = enquiries.length;
  const pageNum = Math.max(1, parseInt(page, 10) || 1);
  const size = Math.min(100, Math.max(1, parseInt(pageSize, 10) || 25));
  const start = (pageNum - 1) * size;
  const paged = enquiries.slice(start, start + size);

  res.json({ enquiries: paged, total, page: pageNum, pageSize: size });
});

app.get('/api/admin/enquiries/export', requireAdminAuth, (req, res) => {
  const enquiries = store.readAll('enquiries.json', []);
  const header = ['Parent Name', 'Child Name', 'Phone', 'Message', 'Status', 'Photo', 'Submitted At'];
  const escapeCsv = (val) => `"${String(val ?? '').replace(/"/g, '""')}"`;

  const rows = enquiries.map(e => [
    e.parentName, e.childName, e.phone, e.message, e.status,
    e.photoUrl || '', e.submittedAt
  ].map(escapeCsv).join(','));

  const csv = [header.map(escapeCsv).join(','), ...rows].join('\n');

  res.setHeader('Content-Type', 'text/csv');
  res.setHeader('Content-Disposition', `attachment; filename="enquiries-${new Date().toISOString().slice(0, 10)}.csv"`);
  res.send(csv);
});

app.patch('/api/admin/enquiries/:id', requireAdminAuth, (req, res) => {
  const { status } = req.body || {};
  const allowed = ['new', 'contacted', 'enrolled', 'closed'];
  if (!allowed.includes(status)) {
    return res.status(400).json({ error: 'Invalid status.' });
  }
  const enquiries = store.readAll('enquiries.json', []);
  const idx = enquiries.findIndex(e => e.id === req.params.id);
  if (idx === -1) return res.status(404).json({ error: 'Enquiry not found.' });
  enquiries[idx].status = status;
  store.writeAll('enquiries.json', enquiries);
  res.json({ success: true, enquiry: enquiries[idx] });
});

/* ------------------------------------------------------------------ *
 * 8. PARENT ACCOUNTS (register / login) -- separate from admin
 * ------------------------------------------------------------------ */

const USER_COOKIE = 'soham_user_token';
const USER_TOKEN_TTL = '30d';

const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 20,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many attempts. Please try again later.' }
});

function requireUserAuth(req, res, next) {
  const token = req.cookies[USER_COOKIE];
  if (!token) return res.status(401).json({ error: 'Not logged in.' });
  try {
    req.user = jwt.verify(token, JWT_SECRET);
    if (req.user.role !== 'user') throw new Error('wrong role');
    next();
  } catch {
    return res.status(401).json({ error: 'Invalid or expired session.' });
  }
}

app.post('/api/auth/register', authLimiter, async (req, res) => {
  const { name, email, phone, password } = req.body || {};
  if (!name || !email || !password) {
    return res.status(400).json({ error: 'Name, email and password are required.' });
  }
  if (password.length < 8) {
    return res.status(400).json({ error: 'Password must be at least 8 characters.' });
  }

  const users = store.readAll('users.json', []);
  const normalizedEmail = String(email).trim().toLowerCase();
  if (users.some(u => u.email === normalizedEmail)) {
    return res.status(409).json({ error: 'An account with this email already exists.' });
  }

  const passwordHash = await bcrypt.hash(password, 12);
  const user = {
    id: crypto.randomUUID(),
    name: String(name).slice(0, 200),
    email: normalizedEmail,
    phone: String(phone || '').slice(0, 40),
    passwordHash,
    createdAt: new Date().toISOString()
  };
  users.push(user);
  store.writeAll('users.json', users);

  const token = jwt.sign({ id: user.id, name: user.name, email: user.email, role: 'user' }, JWT_SECRET, { expiresIn: USER_TOKEN_TTL });
  res.cookie(USER_COOKIE, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
    maxAge: 30 * 24 * 60 * 60 * 1000
  });
  res.json({ success: true, name: user.name });
});

app.post('/api/auth/login', authLimiter, async (req, res) => {
  const { email, password } = req.body || {};
  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required.' });
  }

  const users = store.readAll('users.json', []);
  const normalizedEmail = String(email).trim().toLowerCase();
  const user = users.find(u => u.email === normalizedEmail);
  const passwordMatches = user ? await bcrypt.compare(password, user.passwordHash) : false;

  if (!user || !passwordMatches) {
    return res.status(401).json({ error: 'Invalid email or password.' });
  }

  const token = jwt.sign({ id: user.id, name: user.name, email: user.email, role: 'user' }, JWT_SECRET, { expiresIn: USER_TOKEN_TTL });
  res.cookie(USER_COOKIE, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
    maxAge: 30 * 24 * 60 * 60 * 1000
  });
  res.json({ success: true, name: user.name });
});

app.post('/api/auth/logout', (req, res) => {
  res.clearCookie(USER_COOKIE);
  res.json({ success: true });
});

app.get('/api/auth/me', requireUserAuth, (req, res) => {
  res.json({ name: req.user.name, email: req.user.email });
});

/* ------------------------------------------------------------------ *
 * 9. STATIC SITE + PROTECTED PAGES
 * ------------------------------------------------------------------ */

app.get('/admin/dashboard', requireAdminAuthPage, (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'admin', 'dashboard.html'));
});

app.get('/account', (req, res) => {
  const token = req.cookies[USER_COOKIE];
  if (!token) return res.redirect('/login.html');
  try {
    jwt.verify(token, JWT_SECRET);
    res.sendFile(path.join(__dirname, 'public', 'account.html'));
  } catch {
    return res.redirect('/login.html');
  }
});

app.use(express.static(path.join(__dirname, 'public')));

app.use((req, res) => {
  res.status(404).sendFile(path.join(__dirname, 'public', '404.html'));
});

app.listen(PORT, () => {
  console.log('');
  console.log('==================================================');
  console.log(`Server running on port ${PORT}`);
  if (!process.env.RENDER) {
    console.log(`>>> Open this in your browser: http://localhost:${PORT}`);
    console.log('>>> Do NOT open public/index.html directly as a file -- it will not work.');
  }
  console.log(`Admission window is currently: ${isAdmissionOpen() ? 'OPEN' : 'CLOSED'}`);
  console.log(`Email notifications: ${mailer.isConfigured() ? 'CONFIGURED' : 'not configured (set SMTP_* + NOTIFY_EMAIL to enable)'}`);
  if (licenseAutoGenerated) {
    console.log('[SOHAM.LICENSE] Reminder: license key was auto-generated, not permanent.');
  }
  console.log('==================================================');
  console.log('');
});
